# Generated by Django 3.1.7 on 2021-03-24 16:35

from django.conf import settings
from django.db import migrations, models
import gist.models.activity
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealConfig',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('changed_at', models.DateTimeField(auto_now=True, null=True, verbose_name='changed at')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('breakfast', models.DecimalField(decimal_places=2, default=0.5, help_text='This will consider as meal unit i.e. for breakfast if value set to 0.5 then breakfast consider as half(0.5)', max_digits=5)),
                ('lunch', models.DecimalField(decimal_places=2, default=1, help_text='This will consider as meal unit i.e. for lunch if value set to 1 then lunch consider as one(1)', max_digits=5)),
                ('dinner', models.DecimalField(decimal_places=2, default=1, help_text='This will consider as meal unit i.e. for dinner if value set to 1 then dinner consider as one(1)', max_digits=5)),
                ('add_by', models.ForeignKey(null=True, on_delete=models.SET(gist.models.activity.get_sentinel_user), related_name='configuration_mealconfig_add_by', to=settings.AUTH_USER_MODEL, verbose_name='add by')),
                ('change_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET(gist.models.activity.get_sentinel_user), related_name='configuration_mealconfig_change_by', to=settings.AUTH_USER_MODEL, verbose_name='change by')),
                ('delete_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET(gist.models.activity.get_sentinel_user), related_name='configuration_mealconfig_delete_by', to=settings.AUTH_USER_MODEL, verbose_name='delete by')),
            ],
            options={
                'verbose_name': 'meal_configuration',
                'verbose_name_plural': 'meal_configuration',
                'db_table': 'meal_configuration',
                'ordering': ['-created_at'],
            },
        ),
    ]
