# Generated by Django 3.1.7 on 2021-03-24 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20210324_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
