version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: daybook-backend
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - ENVIRONMENT=production
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=daybook
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_SSLMODE=disable
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - JWT_SECRET=your-jwt-secret-change-this
      - JWT_EXPIRATION=24h
      - CORS_ALLOWED_ORIGINS=http://localhost,http://localhost:3000
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_DURATION=1m
      - MAX_UPLOAD_SIZE=10485760
      - UPLOAD_PATH=/app/uploads
    volumes:
      - backend-uploads:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: daybook-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-uploads:
