server:
  port: 8080
  mode: debug # debug, release

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: daybook
  sslmode: disable
  timezone: UTC

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: your-secret-key-change-this-in-production
  expiration: 168 # hours (7 days)

cors:
  allowed_origins:
    - http://localhost:5173
    - http://localhost:3000
    - http://localhost:3001
  allowed_methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed_headers:
    - Origin
    - Content-Type
    - Authorization
  expose_headers:
    - Content-Length
  allow_credentials: true
  max_age: 12 # hours
