apiVersion: v1
kind: Secret
metadata:
  name: daybook-secrets
  namespace: daybook
type: Opaque
stringData:
  DB_PASSWORD: "123456"
  JWT_SECRET: "your-jwt-secret-change-this-in-production"
  POSTGRES_PASSWORD: "123456"
