# Generated by Django 3.1.7 on 2021-03-23 17:40

import accounts.models.system_user
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import gist.models.activity
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='code')),
                ('add_at', models.DateTimeField(auto_now_add=True, verbose_name='code')),
                ('change_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='change at')),
                ('delete_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='delete at')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('is_organization_admin', models.BooleanField(default=False, verbose_name='organization admin status')),
                ('is_password_change', models.BooleanField(default=False, verbose_name='password change status')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.system_user.user_picture_directory_path, verbose_name='picture')),
                ('add_by', models.ForeignKey(null=True, on_delete=models.SET(gist.models.activity.get_sentinel_user), related_name='accounts_systemuser_add_by', to=settings.AUTH_USER_MODEL, verbose_name='add by')),
                ('change_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET(gist.models.activity.get_sentinel_user), related_name='accounts_systemuser_change_by', to=settings.AUTH_USER_MODEL, verbose_name='change by')),
                ('delete_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET(gist.models.activity.get_sentinel_user), related_name='accounts_systemuser_delete_by', to=settings.AUTH_USER_MODEL, verbose_name='delete by')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'db_table': 'accounts',
                'ordering': ['-add_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
