# Generated by Django 3.1.7 on 2021-03-24 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.RenameField(
            model_name='systemuser',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='add_at',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='change_at',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='is_organization_admin',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='is_password_change',
        ),
        migrations.AddField(
            model_name='systemuser',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='changed at'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
    ]
